Y2020
techheavencz/czech-future-tech pull request #13
Opened 2020-02-25 00:13 UTC by ORngeHead

2020-02-25 00:27 UTC, jakubboucek requested changes
- Některé obrázky jsou neúměrně veliké (v řádu MB) a ve vzájemném nepoměru (`venue_1.jpg` má 136 kB, `venue_3.jpg` má 1,5 MB), `feature_bg.png` má dokonce skoro 5 MB. Navrhuji obrázky ještě zmenšit na nějaký stanovený rozměr a optimalizovat je třeba přes [TinyPNG](https://tinypng.com).
- Prosím URL na CSS soubor inkrementovat o verzi,
- Určitě to už nebude nultý ročník.

2020-02-25 15:46 UTC, ORngeHead commented
- popis akce změním hned co mi bude poslán

2020-02-25 15:46 UTC, jakubboucek commented
Ještě to prosím rebasuj se squashem, aby nezůstalo zbytečných několik MB v historii řepa (dead222d bude fixup commitu 6b27eabc)

2020-02-25 16:57 UTC, ORngeHead commented
všechny obrázky mají pod 1MB

2020-02-27 07:35 UTC, jakubboucek commented
Opravil jsem ten nežádoucí commit 229b6f5. Za mě CR done

2020-02-27 07:35 UTC, jakubboucek approved these changes

2020-02-27 15:18 UTC, merged